// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BannedSubreddit struct {
	ID         string `json:"id"`
	Subreddit  string `json:"subreddit"`
	InsertedAt string `json:"insertedAt"`
}

type BannedSubredditInput struct {
	Subreddit string `json:"subreddit"`
}

type Thread struct {
	ID         string `json:"id"`
	ThreadID   string `json:"threadId"`
	InsertedAt string `json:"insertedAt"`
}
