// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Defines a banned subreddit.
//
// Subreddits are typically saved as banned when the bot fails to respond to comments within a given subreddit.
type BannedSubreddit struct {
	// The name of the subreddit.
	Subreddit string `json:"subreddit"`
	// The UTC ISO-8601 String of when the subreddit was saved as banned.
	InsertedAt string `json:"insertedAt"`
}

type BannedSubredditInput struct {
	// The name of the subreddit.
	//
	// Should exclude the leading 'r/', as this should be up to the caller/client to append if they so wish.
	Subreddit string `json:"subreddit"`
}

// Generic type for removing database rows.
type DeleteMutationResponse struct {
	// Total rows affected by the given delete mutation.
	AffectedRows int `json:"affectedRows"`
}

// Defines a user who has requested to opt-out of the bot fixing their mistakes.
type IgnoredUser struct {
	// The username of the Redditor who refuses to learn Markdown.
	Username string `json:"username"`
	// The UTC ISO-8601 String of when the user requested to be ignored.
	IgnoredAt string `json:"ignoredAt"`
}

type Thread struct {
	ID         string `json:"id"`
	ThreadID   string `json:"threadId"`
	InsertedAt string `json:"insertedAt"`
}
