name: Repository Unit Tests

on:
  push:
    paths:
      - "backend/repository/**"
      - ".github/workflows/repository_test.yaml"

jobs:
  test:
    defaults:
      run:
        working-directory: backend/repository
    strategy:
      matrix:
        go-version: [1.18.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...